# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React build CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
    types: ["merged", "closed"]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported. Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with: 
        type: 'zip'
        filename: 'saraCICD.zip'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
